<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $achievements = [
            // Prestasi Akademik
            [
                'title' => 'Juara 1 Olimpiade Matematika Tingkat Kabupaten',
                'description' => 'Siswa berhasil meraih juara 1 dalam Olimpiade Matematika tingkat kabupaten yang diselenggarakan oleh Dinas Pendidikan.',
                'category' => 'Akademik',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Ahmad Rizki Pratama',
                'date' => '2024-03-15',
                'competition_name' => 'Olimpiade Matematika Kabupaten Buru Selatan',
                'organizer' => 'Dinas Pendidikan Kabupaten Buru Selatan',
                'is_featured' => true,
            ],
            [
                'title' => 'Juara 2 Olimpiade IPA Tingkat Provinsi',
                'description' => 'Tim siswa berhasil meraih juara 2 dalam Olimpiade IPA tingkat provinsi Maluku.',
                'category' => 'Akademik',
                'achievement_level' => 'Provinsi',
                'rank' => 'Juara 2',
                'participant_type' => 'team',
                'participant_names' => 'Siti Nurhaliza, Muhammad Fauzi, Dewi Sartika',
                'date' => '2024-04-20',
                'competition_name' => 'Olimpiade IPA Provinsi Maluku',
                'organizer' => 'Dinas Pendidikan Provinsi Maluku',
                'is_featured' => true,
            ],
            [
                'title' => 'Juara 3 Lomba Debat Bahasa Inggris',
                'description' => 'Tim debat bahasa Inggris berhasil meraih juara 3 dalam lomba debat tingkat kabupaten.',
                'category' => 'Akademik',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 3',
                'participant_type' => 'team',
                'participant_names' => 'Sarah Putri, John Doe, Maria Santos',
                'date' => '2024-05-10',
                'competition_name' => 'Lomba Debat Bahasa Inggris Kabupaten',
                'organizer' => 'MGMP Bahasa Inggris Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 1 Lomba Karya Tulis Ilmiah',
                'description' => 'Siswa berhasil meraih juara 1 dalam lomba karya tulis ilmiah tingkat kabupaten.',
                'category' => 'Akademik',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Rizki Amelia',
                'date' => '2024-06-05',
                'competition_name' => 'Lomba Karya Tulis Ilmiah Remaja',
                'organizer' => 'Dinas Pendidikan dan Kebudayaan Kabupaten Buru Selatan',
                'is_featured' => true,
            ],

            // Prestasi Olahraga
            [
                'title' => 'Juara 1 Sepak Bola Tingkat Kabupaten',
                'description' => 'Tim sepak bola SMP Negeri 01 Namrole berhasil meraih juara 1 dalam turnamen sepak bola tingkat kabupaten.',
                'category' => 'Olahraga',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'team',
                'participant_names' => 'Tim Sepak Bola SMP Negeri 01 Namrole',
                'date' => '2024-08-17',
                'competition_name' => 'Turnamen Sepak Bola HUT RI ke-79',
                'organizer' => 'Pemkab Buru Selatan',
                'is_featured' => true,
            ],
            [
                'title' => 'Juara 2 Basket Putri Tingkat Kabupaten',
                'description' => 'Tim basket putri berhasil meraih juara 2 dalam turnamen basket tingkat kabupaten.',
                'category' => 'Olahraga',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 2',
                'participant_type' => 'team',
                'participant_names' => 'Tim Basket Putri SMP Negeri 01 Namrole',
                'date' => '2024-09-25',
                'competition_name' => 'Turnamen Basket Pelajar Kabupaten',
                'organizer' => 'Dinas Pemuda dan Olahraga Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 1 Bulu Tangkis Tunggal Putra',
                'description' => 'Siswa berhasil meraih juara 1 dalam turnamen bulu tangkis tunggal putra tingkat kabupaten.',
                'category' => 'Olahraga',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Budi Santoso',
                'date' => '2024-10-12',
                'competition_name' => 'Kejuaraan Bulu Tangkis Pelajar',
                'organizer' => 'PB PBSI Kabupaten Buru Selatan',
                'is_featured' => true,
            ],
            [
                'title' => 'Juara 3 Voli Putri Tingkat Kabupaten',
                'description' => 'Tim voli putri berhasil meraih juara 3 dalam turnamen voli tingkat kabupaten.',
                'category' => 'Olahraga',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 3',
                'participant_type' => 'team',
                'participant_names' => 'Tim Voli Putri SMP Negeri 01 Namrole',
                'date' => '2024-11-08',
                'competition_name' => 'Turnamen Voli Pelajar Kabupaten',
                'organizer' => 'Dinas Pemuda dan Olahraga Kabupaten Buru Selatan',
                'is_featured' => false,
            ],

            // Prestasi Seni
            [
                'title' => 'Juara 1 Lomba Tari Tradisional',
                'description' => 'Siswa berhasil meraih juara 1 dalam lomba tari tradisional tingkat kabupaten.',
                'category' => 'Seni',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Sari Dewi',
                'date' => '2024-07-20',
                'competition_name' => 'Festival Seni Budaya Kabupaten',
                'organizer' => 'Dinas Pariwisata dan Kebudayaan Kabupaten Buru Selatan',
                'is_featured' => true,
            ],
            [
                'title' => 'Juara 2 Lomba Menyanyi Solo',
                'description' => 'Siswa berhasil meraih juara 2 dalam lomba menyanyi solo tingkat kabupaten.',
                'category' => 'Seni',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 2',
                'participant_type' => 'individual',
                'participant_names' => 'Maya Sari',
                'date' => '2024-08-25',
                'competition_name' => 'Festival Musik Pelajar',
                'organizer' => 'Dinas Pendidikan dan Kebudayaan Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 1 Lomba Lukis Tingkat Kabupaten',
                'description' => 'Siswa berhasil meraih juara 1 dalam lomba lukis tingkat kabupaten.',
                'category' => 'Seni',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Andi Wijaya',
                'date' => '2024-09-15',
                'competition_name' => 'Lomba Lukis Pelajar',
                'organizer' => 'Dinas Pendidikan dan Kebudayaan Kabupaten Buru Selatan',
                'is_featured' => true,
            ],

            // Prestasi Lain-lain
            [
                'title' => 'Juara 1 Lomba Pramuka Tingkat Kabupaten',
                'description' => 'Regu pramuka berhasil meraih juara 1 dalam lomba pramuka tingkat kabupaten.',
                'category' => 'Lain-lain',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'team',
                'participant_names' => 'Regu Pramuka SMP Negeri 01 Namrole',
                'date' => '2024-10-05',
                'competition_name' => 'Jambore Pramuka Kabupaten',
                'organizer' => 'Kwarcab Gerakan Pramuka Kabupaten Buru Selatan',
                'is_featured' => true,
            ],
            [
                'title' => 'Juara 2 Lomba PMR Tingkat Kabupaten',
                'description' => 'Tim PMR berhasil meraih juara 2 dalam lomba PMR tingkat kabupaten.',
                'category' => 'Lain-lain',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 2',
                'participant_type' => 'team',
                'participant_names' => 'Tim PMR SMP Negeri 01 Namrole',
                'date' => '2024-11-20',
                'competition_name' => 'Lomba PMR Pelajar',
                'organizer' => 'PMI Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 1 Lomba Karya Ilmiah Remaja',
                'description' => 'Siswa berhasil meraih juara 1 dalam lomba karya ilmiah remaja tingkat kabupaten.',
                'category' => 'Lain-lain',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Nurul Hidayah',
                'date' => '2024-12-10',
                'competition_name' => 'Lomba Karya Ilmiah Remaja',
                'organizer' => 'Dinas Pendidikan dan Kebudayaan Kabupaten Buru Selatan',
                'is_featured' => true,
            ],

            // Prestasi Tahun 2023
            [
                'title' => 'Juara 1 Olimpiade Matematika Tingkat Kabupaten 2023',
                'description' => 'Siswa berhasil meraih juara 1 dalam Olimpiade Matematika tingkat kabupaten tahun 2023.',
                'category' => 'Akademik',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Rizki Pratama',
                'date' => '2023-03-20',
                'competition_name' => 'Olimpiade Matematika Kabupaten Buru Selatan',
                'organizer' => 'Dinas Pendidikan Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 2 Sepak Bola Tingkat Kabupaten 2023',
                'description' => 'Tim sepak bola berhasil meraih juara 2 dalam turnamen sepak bola tingkat kabupaten tahun 2023.',
                'category' => 'Olahraga',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 2',
                'participant_type' => 'team',
                'participant_names' => 'Tim Sepak Bola SMP Negeri 01 Namrole',
                'date' => '2023-08-17',
                'competition_name' => 'Turnamen Sepak Bola HUT RI ke-78',
                'organizer' => 'Pemkab Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 1 Lomba Tari Tradisional 2023',
                'description' => 'Siswa berhasil meraih juara 1 dalam lomba tari tradisional tingkat kabupaten tahun 2023.',
                'category' => 'Seni',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'individual',
                'participant_names' => 'Sari Dewi',
                'date' => '2023-07-25',
                'competition_name' => 'Festival Seni Budaya Kabupaten',
                'organizer' => 'Dinas Pariwisata dan Kebudayaan Kabupaten Buru Selatan',
                'is_featured' => false,
            ],

            // Prestasi Tahun 2022
            [
                'title' => 'Juara 3 Olimpiade IPA Tingkat Kabupaten 2022',
                'description' => 'Tim siswa berhasil meraih juara 3 dalam Olimpiade IPA tingkat kabupaten tahun 2022.',
                'category' => 'Akademik',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 3',
                'participant_type' => 'team',
                'participant_names' => 'Tim Olimpiade IPA SMP Negeri 01 Namrole',
                'date' => '2022-04-15',
                'competition_name' => 'Olimpiade IPA Kabupaten Buru Selatan',
                'organizer' => 'Dinas Pendidikan Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
            [
                'title' => 'Juara 1 Lomba Pramuka Tingkat Kabupaten 2022',
                'description' => 'Regu pramuka berhasil meraih juara 1 dalam lomba pramuka tingkat kabupaten tahun 2022.',
                'category' => 'Lain-lain',
                'achievement_level' => 'Kecamatan',
                'rank' => 'Juara 1',
                'participant_type' => 'team',
                'participant_names' => 'Regu Pramuka SMP Negeri 01 Namrole',
                'date' => '2022-10-10',
                'competition_name' => 'Jambore Pramuka Kabupaten',
                'organizer' => 'Kwarcab Gerakan Pramuka Kabupaten Buru Selatan',
                'is_featured' => false,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::create($achievement);
        }
    }
}

