<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Registration;
use App\Models\RegistrationSetting;
use App\Models\AcademicYear;
use App\Models\RegistrationDocument;
use Illuminate\Support\Str;

class SampleRegistrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currentYear = AcademicYear::where('is_active', true)->first();
        $setting = RegistrationSetting::where('academic_year_id', $currentYear->id)->first();

        if (!$setting) {
            $this->command->warn('Tidak ada pengaturan PPDB. Jalankan RegistrationSettingSeeder terlebih dahulu.');
            return;
        }

        $sampleData = [
            [
                'full_name' => 'Ahmad Rizki Pratama',
                'nik' => '1234567890123456',
                'nisn' => '1234567890',
                'birth_place' => 'Jakarta',
                'birth_date' => '2010-05-15',
                'gender' => 'L',
                'religion' => 'Islam',
                'child_number' => 1,
                'siblings_count' => 2,
                'address' => 'Jl. Merdeka No. 123',
                'rt' => '001',
                'rw' => '005',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10310',
                'phone' => '081234567890',
                'email' => 'ahmad.rizki@email.com',
                'height' => 150,
                'weight' => 45,
                'blood_type' => 'O',
                'father_name' => 'Budi Pratama',
                'father_nik' => '1234567890123457',
                'father_birth_year' => 1980,
                'father_education' => 'S1',
                'father_occupation' => 'PNS',
                'father_income' => 'Rp 5.000.000 - Rp 10.000.000',
                'father_phone' => '081234567891',
                'mother_name' => 'Siti Aminah',
                'mother_nik' => '1234567890123458',
                'mother_birth_year' => 1982,
                'mother_education' => 'S1',
                'mother_occupation' => 'Guru',
                'mother_income' => 'Rp 3.000.000 - Rp 5.000.000',
                'mother_phone' => '081234567892',
                'previous_school' => 'SD Negeri 01 Menteng',
                'school_npsn' => '12345678',
                'school_address' => 'Jl. Pendidikan No. 1, Jakarta Pusat',
                'graduation_year' => 2024,
                'certificate_number' => 'IJZ/2024/001',
                'average_score' => 85.5,
                'achievements' => 'Juara 1 Olimpiade Matematika Tingkat Kecamatan',
                'registration_path' => 'achievement',
                'status' => 'accepted',
            ],
            [
                'full_name' => 'Siti Nurhaliza',
                'nik' => '1234567890123459',
                'nisn' => '1234567891',
                'birth_place' => 'Bandung',
                'birth_date' => '2010-08-20',
                'gender' => 'P',
                'religion' => 'Islam',
                'child_number' => 2,
                'siblings_count' => 3,
                'address' => 'Jl. Pendidikan No. 456',
                'rt' => '002',
                'rw' => '006',
                'kelurahan' => 'Cikini',
                'kecamatan' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10330',
                'phone' => '081234567893',
                'email' => 'siti.nurhaliza@email.com',
                'height' => 145,
                'weight' => 42,
                'blood_type' => 'A',
                'father_name' => 'Ahmad Hidayat',
                'father_nik' => '1234567890123460',
                'father_birth_year' => 1978,
                'father_education' => 'SMA',
                'father_occupation' => 'Wiraswasta',
                'father_income' => 'Rp 2.000.000 - Rp 5.000.000',
                'father_phone' => '081234567894',
                'mother_name' => 'Rohani',
                'mother_nik' => '1234567890123461',
                'mother_birth_year' => 1980,
                'mother_education' => 'SMA',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'mother_income' => 'Tidak Berpenghasilan',
                'mother_phone' => '081234567895',
                'previous_school' => 'SD Islam Terpadu Al-Azhar',
                'school_npsn' => '87654321',
                'school_address' => 'Jl. Sisingamangaraja No. 1, Jakarta Selatan',
                'graduation_year' => 2024,
                'certificate_number' => 'IJZ/2024/002',
                'average_score' => 88.0,
                'registration_path' => 'regular',
                'status' => 'accepted',
            ],
            [
                'full_name' => 'Budi Santoso',
                'nik' => '1234567890123462',
                'nisn' => '1234567892',
                'birth_place' => 'Surabaya',
                'birth_date' => '2010-03-10',
                'gender' => 'L',
                'religion' => 'Kristen',
                'child_number' => 1,
                'siblings_count' => 1,
                'address' => 'Jl. Kemerdekaan No. 789',
                'rt' => '003',
                'rw' => '007',
                'kelurahan' => 'Gambir',
                'kecamatan' => 'Gambir',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10110',
                'phone' => '081234567896',
                'email' => 'budi.santoso@email.com',
                'height' => 155,
                'weight' => 48,
                'blood_type' => 'B',
                'father_name' => 'Santoso',
                'father_nik' => '1234567890123463',
                'father_birth_year' => 1975,
                'father_education' => 'SMP',
                'father_occupation' => 'Buruh',
                'father_income' => 'Rp 1.000.000 - Rp 2.000.000',
                'father_phone' => '081234567897',
                'mother_name' => 'Sari',
                'mother_nik' => '1234567890123464',
                'mother_birth_year' => 1977,
                'mother_education' => 'SMP',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'mother_income' => 'Tidak Berpenghasilan',
                'mother_phone' => '081234567898',
                'previous_school' => 'SD Negeri 02 Gambir',
                'school_npsn' => '11223344',
                'school_address' => 'Jl. Merdeka Selatan No. 2, Jakarta Pusat',
                'graduation_year' => 2024,
                'certificate_number' => 'IJZ/2024/003',
                'average_score' => 82.0,
                'registration_path' => 'affirmation',
                'status' => 'accepted',
            ],
            [
                'full_name' => 'Maya Sari',
                'nik' => '1234567890123465',
                'nisn' => '1234567893',
                'birth_place' => 'Medan',
                'birth_date' => '2010-11-25',
                'gender' => 'P',
                'religion' => 'Islam',
                'child_number' => 3,
                'siblings_count' => 4,
                'address' => 'Jl. Kebon Jeruk No. 321',
                'rt' => '004',
                'rw' => '008',
                'kelurahan' => 'Kebon Jeruk',
                'kecamatan' => 'Kebon Jeruk',
                'city' => 'Jakarta Barat',
                'province' => 'DKI Jakarta',
                'postal_code' => '11530',
                'phone' => '081234567899',
                'email' => 'maya.sari@email.com',
                'height' => 148,
                'weight' => 44,
                'blood_type' => 'AB',
                'father_name' => 'Rahmat',
                'father_nik' => '1234567890123466',
                'father_birth_year' => 1972,
                'father_education' => 'SMA',
                'father_occupation' => 'Sopir',
                'father_income' => 'Rp 2.000.000 - Rp 3.000.000',
                'father_phone' => '081234567900',
                'mother_name' => 'Siti',
                'mother_nik' => '1234567890123467',
                'mother_birth_year' => 1974,
                'mother_education' => 'SMA',
                'mother_occupation' => 'Penjual',
                'mother_income' => 'Rp 1.500.000 - Rp 2.500.000',
                'mother_phone' => '081234567901',
                'previous_school' => 'SD Swasta Al-Ikhlas',
                'school_npsn' => '55667788',
                'school_address' => 'Jl. Raya Kebon Jeruk No. 10, Jakarta Barat',
                'graduation_year' => 2024,
                'certificate_number' => 'IJZ/2024/004',
                'average_score' => 79.5,
                'registration_path' => 'regular',
                'status' => 'pending',
            ],
            [
                'full_name' => 'Rizki Aditya',
                'nik' => '1234567890123468',
                'nisn' => '1234567894',
                'birth_place' => 'Yogyakarta',
                'birth_date' => '2010-07-12',
                'gender' => 'L',
                'religion' => 'Islam',
                'child_number' => 2,
                'siblings_count' => 2,
                'address' => 'Jl. Veteran No. 654',
                'rt' => '005',
                'rw' => '009',
                'kelurahan' => 'Menteng',
                'kecamatan' => 'Menteng',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10310',
                'phone' => '081234567902',
                'email' => 'rizki.aditya@email.com',
                'height' => 152,
                'weight' => 46,
                'blood_type' => 'O',
                'father_name' => 'Aditya',
                'father_nik' => '1234567890123469',
                'father_birth_year' => 1976,
                'father_education' => 'S1',
                'father_occupation' => 'Dokter',
                'father_income' => 'Rp 10.000.000 - Rp 20.000.000',
                'father_phone' => '081234567903',
                'mother_name' => 'Dewi',
                'mother_nik' => '1234567890123470',
                'mother_birth_year' => 1978,
                'mother_education' => 'S1',
                'mother_occupation' => 'Perawat',
                'mother_income' => 'Rp 5.000.000 - Rp 10.000.000',
                'mother_phone' => '081234567904',
                'previous_school' => 'SD Negeri 03 Menteng',
                'school_npsn' => '99887766',
                'school_address' => 'Jl. Diponegoro No. 3, Jakarta Pusat',
                'graduation_year' => 2024,
                'certificate_number' => 'IJZ/2024/005',
                'average_score' => 92.0,
                'achievements' => 'Juara 1 Olimpiade Sains Tingkat Kota, Juara 2 Lomba Cerdas Cermat',
                'registration_path' => 'achievement',
                'status' => 'accepted',
            ],
        ];

        foreach ($sampleData as $data) {
            $registration = Registration::create(array_merge($data, [
                'academic_year_id' => $currentYear->id,
                'registration_setting_id' => $setting->id,
                'photo' => 'sample_photo_' . Str::random(10) . '.jpg',
                'verified_at' => $data['status'] !== 'pending' ? now() : null,
                'verified_by' => $data['status'] !== 'pending' ? 1 : null,
                'announced_at' => $data['status'] === 'accepted' ? now() : null,
            ]));

            // Create sample documents
            $documentTypes = ['photo', 'ijazah', 'kk', 'akta'];
            foreach ($documentTypes as $type) {
                RegistrationDocument::create([
                    'registration_id' => $registration->id,
                    'document_type' => $type,
                    'file_name' => 'sample_' . $type . '_' . Str::random(10) . '.pdf',
                    'file_path' => 'registrations/' . $registration->registration_number . '/sample_' . $type . '_' . Str::random(10) . '.pdf',
                    'file_size' => rand(100000, 2000000),
                    'mime_type' => 'application/pdf',
                    'is_verified' => $data['status'] !== 'pending',
                    'verified_by' => $data['status'] !== 'pending' ? 1 : null,
                    'verified_at' => $data['status'] !== 'pending' ? now() : null,
                ]);
            }

            // Create achievement documents for achievement path
            if ($registration->registration_path === 'achievement' && $registration->achievements) {
                RegistrationDocument::create([
                    'registration_id' => $registration->id,
                    'document_type' => 'achievement',
                    'file_name' => 'sertifikat_prestasi_' . Str::random(10) . '.pdf',
                    'file_path' => 'registrations/' . $registration->registration_number . '/sertifikat_prestasi_' . Str::random(10) . '.pdf',
                    'file_size' => rand(500000, 3000000),
                    'mime_type' => 'application/pdf',
                    'is_verified' => $data['status'] !== 'pending',
                    'verified_by' => $data['status'] !== 'pending' ? 1 : null,
                    'verified_at' => $data['status'] !== 'pending' ? now() : null,
                ]);
            }
        }

        $this->command->info('Sample registrations created successfully!');
    }
}

